server:
  port: 5007

powsybl:
  services:
    network-store-server:
      base-uri: http://localhost:8080

network-store-server:
  base-uri: http://localhost:8080

gridsuite:
  services:
    report-server:
      base-uri: http://localhost:5028
    filter-server:
      base-uri: http://localhost:5027

spring:
  rabbitmq:
    addresses: localhost
  data:
    elasticsearch:
      host: localhost
      ## to fill if authentication is needed
      # user:
      # password:

powsybl-ws:
  database:
    host: localhost
