spring:
  application:
    name: netork-modification-server

  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 5007

network-store-server:
  base-uri: http://localhost:8080
