server:
  port: 5007

powsybl:
  services:
    network-store-server:
      base-uri: http://localhost:8080

gridsuite:
  services:
    report-server:
      base-uri: http://localhost:5028
    filter-server:
      base-uri: http://localhost:5027
    loadflow-server:
      base-uri: http://localhost:5008

spring:
  rabbitmq:
    addresses: localhost
  elasticsearch:
    uris:
      - http://localhost:9200
  ## to fill if authentication is needed
  # username:
  # password:

powsybl-ws:
  database:
    host: localhost
