server:
  port: 5007

network-store-server:
  base-uri: http://localhost:8080

backing-services:
  report-server:
    base-uri: http://localhost:5028

spring:
  data:
    elasticsearch:
      host: localhost
