server:
  port: 5007

network-store-server:
  base-uri: http://localhost:8080

backing-services:
  report-server:
    base-uri: http://localhost:5028

spring:
  rabbitmq:
    addresses: localhost
  data:
    elasticsearch:
      host: localhost
      user: elastic
      password: elastic
