/*
 * Copyright (c) 2026, RTE (http://www.rte-france.com)
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */
package org.gridsuite.modification.server.entities;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.BatchSize;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * @author Hugo Marcellin {@literal <hugo.marcelin at rte-france.com>}
 */
@Getter
@NoArgsConstructor
@Entity
@Inheritance(strategy = InheritanceType.JOINED)
@DiscriminatorColumn(name = "container_type", discriminatorType = DiscriminatorType.STRING, length = 32)
@Table(name = "modification_container")
public abstract class AbstractModificationContainerEntity extends AbstractManuallyAssignedIdentifierEntity<UUID> implements ModificationContainer {

    @Id
    @Column(name = "id")
    private UUID id;

    // The constraint name is generated by liquibase
    @OneToMany(mappedBy = "container", cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH, CascadeType.DETACH})
    @OrderBy("modificationsOrder asc")
    private final List<ModificationEntity> modifications = new ArrayList<>();

    protected AbstractModificationContainerEntity(UUID id) {
        this.id = id;
    }

    @Override
    public void addModification(ModificationEntity child, int position) {
        int target = Math.clamp(position, 0, modifications.size());
        child.attachToContainer(this);
        modifications.add(target, child);
        for (int i = 0; i < modifications.size(); i++) {
            modifications.get(i).setModificationsOrder(i);
        }
    }

    /**
     * Replace the whole list. Re-numbers {@code modificationsOrder} and re-points each child at
     * this container. Used during initial load / re-ordering operations.
     */
    @Override
    public void setModifications(List<ModificationEntity> newChildren) {
        List<ModificationEntity> incoming = newChildren == null ? List.of() : new ArrayList<>(newChildren);
        this.modifications.clear();
        for (int i = 0; i < incoming.size(); i++) {
            ModificationEntity child = incoming.get(i);
            child.attachToContainer(this);
            child.setModificationsOrder(i);
            this.modifications.add(child);
        }
    }
}

